title: 'k_shell'
description: "Simple Shell"

header_pages:
  - index.md
  - peter.md
  - about.md
  - contact.md

style: dark

footer: 'follow us on <a href="https://github.com/davixcky/simple_shell/" target="_blank">github</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
