title: 'k_shell'
description: "Simple Shell"

header_pages:
  - index.md
  - file_IO.md
  - signals.md
  - environment_variables.md
  - child_and_process.md
  - shell_basic.md
  - example l -ls.md

style: dark

footer: 'follow us on <a href="https://github.com/davixcky/simple_shell/" target="_blank">github</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
